###################
# Runtime Secrets #
###################
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
# values must be base64 encoded before creating/modifying the secret
# use `echo -n 'value' | base64` to prevent newlines from being added to the secret
# if a newline was accidentally added, the secret will end with "o=" and will not work
data:
  SECRET_KEY_BASE: aW5jcmVkaWJseXN1cGVyc2VjcmV0
  ERLANG_COOKIE: c3VwZXJzZWNyZXRjb29raWU=
