##############
# Deployment # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
##############

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          command: ["elixir"]
          args:
            [
              "-S",
              "mix",
              "phx.server",
            ]
          image: localhost:32000/demo:latest # replaced by rebuild_push_deploy.sh
          ports:
            - name: http-port
              containerPort: 4000