##############
# Deployment # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
##############

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          command: ["elixir"]
          args:
            [
              "--erl",
              "-kernel inet_dist_listen_min 5000 -kernel inet_dist_listen_max 5000",
              "--name",
              "demo@$(MY_POD_IP)",
              "--cookie",
              "$(ERLANG_COOKIE)",
              "-S",
              "mix",
              "phx.server",
            ]
          image: localhost:32000/demo:latest # replaced by rebuild_push_deploy.sh
          ports:
            - name: http-port
              containerPort: 4000
            - name: epmd-port
              containerPort: 4369
            - name: beam-port
              containerPort: 5000
          env:
            - name: MY_POD_IP # Used as Erlang VM node name
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP      
            - name: ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: ERLANG_COOKIE
            - name: NODE_DISCOVERY_DNS_NAME
              value: demo-backend-service-headless.default.svc.cluster.local