############
# Services # https://kubernetes.io/docs/concepts/services-networking/service/
############

# The main service that is exposed to the ingress / load balancer
# Reachable at its ClusterIP when using microk8s
# kubectl get svc demo-backend-service
---
kind: Service
apiVersion: v1
metadata:
  name: demo-backend-service
  labels:
    k8s-app: demo-backend # for monitoring discovery
spec:
  type: ClusterIP # normally a clusterip service is unreachable for the outside world, but not with microk8s
  selector:
    app: demo
  ports:
    - name: http-port
      port: 4000
      targetPort: 4000
      protocol: TCP

# Headless backend service (for Elixir/Erlang node discovery)
---
kind: Service
apiVersion: v1
metadata:
  name: demo-backend-service-headless
spec:
  type: ClusterIP
  selector:
    app: demo
  clusterIP: None # Headless service - it does not have an IP of its own but exposes the IP's of the pods themselves
  ports:
    - port: 8000 # Nonsense, unused port. A headless service needs one (:|) as a workaround for a Kubernetes bug
